porocollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('poros/', views.poro_index, name= 'index'),
    path('poros/<int:poro_id>/', views.poros_detail, name='detail'),
    path('poros/create/', views.PoroCreate.as_view(), name='poros_create'),
    path('poros/<int:pk>/update', views.PoroUpdate.as_view(), name='poros_update'),
    path('poros/<int:pk>/delete', views.PoroDelete.as_view(), name='poros_delete'),
    path('poros/<int:poro_id>/add_feeding', views.add_feeding, name='add_feeding'),
    # CRUD for Toys using CBV's
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),

    # Associate a toy with a poro (M:M)
    path('poros/<int:poro_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),

    # Unassociate / Disassociate a toy with a poro (M:M)
    path('poros/<int:poro_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),

    #sign-up
    path('accounts/signup/', views.signup, name='signup')
]

porocollector/porocollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path ('accounts/',include('django.contrib.auth.urls'))
]

porocollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

REGIONS = (
    ('F','Freljord'),
    ('D','Demacia'),
    ('I','Ionia'),
    ('N','Noxus'),
    ('P','Piltover & Zaun'),
    ('S','Shadow Isles'),
    ('B','Bilgewater'),
    ('T','Targon'),
    ('SH','Shurima'),
    ('BC','Bandle City'),
    ('R','Runterra')
)

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse ('toys_detail', kwargs={'pk': self.id})

class Poro(models.Model):
    name= models.CharField(max_length=100)
    region= models.CharField(max_length=100, choices=REGIONS, default=REGIONS[0][0])
    description= models.TextField(max_length=250)
    image = models.ImageField(upload_to='main_app/static/uploads/', default='')
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'poro_id':self.id})
    
    def __str__(self):
        return self.name
    
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >=3  
    
class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(max_length=1, choices= MEALS, default=MEALS[0][0])
    poro = models.ForeignKey(Poro, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date} for {self.poro}'

porocollector/main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

porocollector/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Poro, Toy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import FeedingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class PoroCreate(LoginRequiredMixin, CreateView):
    model = Poro
    # fields = '__all__'
    fields = ['name', 'region', 'description', 'image']

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PoroUpdate(UpdateView):
    model = Poro
    fields = ['name', 'description', 'image']

class PoroDelete(DeleteView):
    model = Poro
    success_url = '/poros/'
    
class ToyList(ListView):
    model = Toy

class ToyDetail(DetailView):
    model = Toy

class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']
    #can write __all__ ^^

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def poro_index(request):
    poros = Poro.objects.filter(user=request.user)
    return render(request, 'poros/index.html', {'poros': poros})

@login_required
def poros_detail(request, poro_id):
    poro = Poro.objects.get(id = poro_id)
    feeding_form = FeedingForm()
    toys_poro_doesnt_have = Toy.objects.exclude(id__in = poro.toys.all().values_list('id'))
    return render(request, 'poros/detail.html',{'poro':poro, 'feeding_form' : feeding_form, 'toys' : toys_poro_doesnt_have})

@login_required
def add_feeding(request, poro_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit = False)
        new_feeding.poro_id = poro_id
        new_feeding.save()

    return redirect('detail', poro_id = poro_id)

@login_required
def assoc_toy(request, poro_id, toy_id):
    print("poro_id, toy_id", poro_id, toy_id)
    Poro.objects.get(id = poro_id).toys.add(toy_id)
    return redirect('detail', poro_id = poro_id)

@login_required
def unassoc_toy(request, poro_id, toy_id):
    Poro.objects.get(id = poro_id).toys.remove(toy_id)
    return redirect('detail', poro_id = poro_id)


def signup(request):
    error_message=''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('index')
        
        else:
            error_message = 'Invalid Sign-up please try again later.'

    form = UserCreationForm()
    context = {'form':form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

porocollector/main_app/templates/about.html
{%extends 'base.html' %}

{%block content%}
  <h1>About the Poro Collector App</h1>
  <br>
  <p>Hire the Poro Collector</p>
{% endblock %}

porocollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Poro Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left-brand-logo">
                &nbsp;&nbsp; Poro Collector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'poros_create' %}">Add a Poro</a></li>
            <li><a href="{% url 'index' %}">View all my Poros</a></li>
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
            <li>
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log out!</button>
              </form>
            </li>
            Hi {{user.username}} 
            {% else %}
            <li>
              <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
              <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{%block content%} {%endblock%}</main>
    <footer class="page-footer">
      <div class="right">
        All rights Reserved, &copy; 2025 Poro Collector &nbsp
      </div>
    </footer>
  </body>
</html>

porocollector/main_app/templates/home.html
{%extends 'base.html' %}

{%block content%}
  <h1>Poro Collector App</h1>
  <hr>
{% endblock %}

porocollector/main_app/templates/main_app/poro_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Poro</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' poro.id %}" class="btn red">Cancel</a>
  </form>
{% endblock %}

porocollector/main_app/templates/main_app/poro_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Poro</h1>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

<script>
  let selectEl = document.getElementById('id_region');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

porocollector/main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

porocollector/main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>

      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>

    </div>
  </div>
</div>
{% endblock %}

porocollector/main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

porocollector/main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

porocollector/main_app/templates/poros/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Poro Detail</h1>
<div class="card">
  <div class="card-content">
    <div class="right">
      {% load static %}
      <img
        src="{% static poro.image|cut:'main_app/static/' %}"
        width="100px"
        height="100px"
      />
    </div>
    <span class="card-title">{{ poro.name }}</span>
    <p>Region: {{ poro.get_region_display }}</p>
    <p>Description: {{ poro.description }}</p>
    <br />
    <div class="card-section">
      <a href="{% url 'poros_update' poro.id%}">Edit</a>
      <a href="{% url 'poros_delete' poro.id%}">Delete</a>
    </div>
  </div>
</div>

<div>
  <form action="{% url 'add_feeding' poro.id %}" method="post">
    {% csrf_token %} {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding" />
  </form>
</div>

{% if poro.fed_for_today %}
<div class="card-panel teal-text center-align">
  {{poro.name}} has been fed all meals for today
</div>
{% else %}
<div class="card-panel red-text center-align">
  {{poro.name}} might be hungry
</div>
{% endif %}

<div>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Meal</th>
      </tr>
    </thead>

    <tbody>
      {% for feeding in poro.feeding_set.all %}
      <tr>
        <td>{{ feeding.date }}</td>
        <td>{{ feeding.get_meal_display }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<hr />

<div class="row">
  <div class="col s6">
    <h3>{{ poro.name }}'s Toys</h3>

    {% if poro.toys.count %} {% for toy in poro.toys.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A
          <span style="color: {{toy.color}}">{{toy.color}}</span> {{toy.name}}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_toy' poro.id toy.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Toys :(</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Toys</h3>

    {% if toys.count %} {% for toy in toys.all%}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{toy.color}}">{{toy.color}}</span> {{toy.name}}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_toy' poro.id toy.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{ poro.name }} already has all toys available.</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date')
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  })

  let selectEl = document.getElementById('id_meal')
  M.FormSelect.init(selectEl)
</script>

{% endblock %}

porocollector/main_app/templates/poros/index.html
{% extends 'base.html' %}

{%block content%}

<h1>Poro List</h1>

{% for poro in poros%}
  <div class="card">
    <a href="{% url 'detail' poro.id %}">
    <div class="card-content">
      <div class="right">
        {%load static%}
        <img src="{%static poro.image|cut:'main_app/static/'%}" width="100px" height="100px">
      </div>
      <span class="card-title">{{poro.name}}</span>
      <br>
      <p>Description: {{poro.description}}</p>
    </div>
  </a>
  </div>
{%endfor%}

{%endblock%}